name: Linux

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [g++-11, clang++-13]
        flags: [-std=c++20]
        optimize: [-O2]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Install g++
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install -y g++-11
    - name: Set up Clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 13
        platform: x64
    - name: Build and test
      env:
        CXX: ${{ matrix.compiler }}
        CXXFLAGS: ${{ matrix.flags }} ${{ matrix.optimize }}
      run: |
        mkdir build && cd build && cmake -DPHMAP_BUILD_TESTS=ON -DPHMAP_BUILD_EXAMPLES=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && make test
